var question_finisher_1 = require('../question-finisher');
var question_responder_1 = require('../question-responder');
var reply_to_reply_1 = require('../reply-to-reply');
var anchor_coloring_1 = require('../anchor-coloring');
window.QuestionFinisher = question_finisher_1.default;
window.QuestionResponder = question_responder_1.default;
window.ReplyToReply = reply_to_reply_1.default;
window.AnchorColoring = anchor_coloring_1.default;
//# sourceMappingURL=index.js.map