default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: askable_development

test:
  adapter: sqlite3
  database: ":memory:"
  pool: 5
  timeout: 5000

production:
  <<: *default
  database: askable_production
