var React = require('react');
var ReactDOM = require('react-dom');
var _ = require('lodash');
var Promise = require('bluebird');
var request = require('superagent');
var events_1 = require('events');
window.React = React;
window.ReactDOM = ReactDOM;
window._ = _;
window.EventEmitter = events_1.EventEmitter;
window.Promise = Promise;
window.request = request;
//# sourceMappingURL=index.js.map